export const CATEGORIES = [
  "Gaming",
  "Fashion",
  "Lifestyle",
  "Travel",
  "Food & Cooking",
  "Tech",
  "Fitness",
  "Health & Wellness",
  "Beauty & Skincare",
  "Education",
  "Finance & Investing",
  "Parenting & Family",
  "Automobile (Cars & Bikes)",
  "Entertainment",
  "Comedy & Memes",
  "Motivation & Self Growth",
  "Business & Entrepreneurship",
  "Photography",
  "Videography",
  "Home Decor & Interior",
  "DIY & Crafts",
  "Pets & Animals",
  "Music & Singing",
  "Dance",
  "Art & Illustration",
  "Spirituality & Astrology",
  "News & Politics",
  "Other"
];
